# Generated by Django 4.2 on 2026-01-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
